thruster_controller:
  ros__parameters:
    max_thrust: 1000.0
    max_linear_velocity: 1.0
    max_angular_velocity: 0.3
    control_rate: 20.0
    linear_pid_kp: 200.0
    linear_pid_ki: 5.0
    linear_pid_kd: 20.0
    angular_pid_kp: 600.0
    angular_pid_ki: 5.0
    angular_pid_kd: 80.0